module.exports = {
  brew: [
    'ack',
    'annie',
    'bat',
    'catimg',
    // Install GNU core utilities (those that come with OS X are outdated)
    // Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
    'coreutils',
    'dos2unix',
    'doitlive',
    'emojify',
    // Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed
    'findutils',
    'fd',
    'fortune',
    //'gawk',
    // http://www.lcdf.org/gifsicle/ (because I'm a gif junky)
    'gifsicle',
    'gnupg',
    // Install GNU `sed`, overwriting the built-in `sed`
    // so we can do "sed -i 's/foo/bar/' file" instead of "sed -i '' 's/foo/bar/' file"
    'gnu-sed --default-names',
    'gzip',
    'graphviz',
    'grip',
    'httpie',
    'lolcat',
    'make',
    'npm',
    'less',
    'openssh',
    'rsync',
    'unzip',
    // better, more recent grep
    'homebrew/dupes/grep',
    'imagemagick',
    'imagesnap',
    // jq is a sort of JSON grep
    'jq',
    // yq is a sort of YAML grep
    'yq',
    // Install some other useful utilities like `sponge`
    'moreutils',
    'nmap',
    'openconnect',
    'plantuml',
    'python',
    'clojure',
    'leiningen',
    'reattach-to-user-namespace',
    // better/more recent version of screen
    'homebrew/dupes/screen',
    'tmux',
    'thefuck',
    'tldr',
    'tree',
    'ttyrec',
    // better, more recent vim
    'vim --override-system-vi',
    'watch',
    // Install wget with IRI support
    'wget --enable-iri'
  ],
  cask: [
    //'adium',
    //'amazon-cloud-drive',
    //'android-studio',
    //'atom',
    //'diffmerge',
    'emacs',
    //'cyberduck',
    'evernote',
    'geogebra',
    'gpgtools',
    //'ireadfast',
    'java',
    //'macvim',
    //'cinch',
    'sizeup',
    //'tuck',
    //'sketchup',
    //'radian-player',
    //'gitter',
    //'slack',
    'skitch',
    'skype',
    'the-unarchiver',
    //'pycharm-ce',
    //'pocketcast',
    //'picasa',
    //'torbrowser',
    'transmission',
    'vlc',
    //'elmedia-player',
    //'thebrain',
    //'swi-prolog',
    //'vagrant',
    //'visual-studio-code',
    //'virtualbox',
    //'virtualbox-extension-pack',
    'xquartz'
  ],
  apt: [
    'ack-grep',
    //'atom',
    'cowsay',
    'emacs',
    'fortune',
    'fd-find',
    'lolcat',
    'firefox',
    'graphviz',
    'oracle-java8-installer',
    'oracle-java8-set-default',
    'redshift-gtk',
    'swi-prolog',
    //'vagrant',
    //'virtualbox',
    'terminator',
    'tmux'
  ]
};
